wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1647447233
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      - 13
      4: 3.9.7
      5: 0.12.11
      8:
      - 1
      - 5
      10:
      - 5
    viz:
      feature_importances:
        historyFieldSettings:
          key: feature_importances
          x-axis: _step
        id: wandb/feature_importances/v1
      learning_curve:
        historyFieldSettings:
          key: learning_curve
          x-axis: _step
        id: wandb/learning_curve/v1
