program: mlpc_train.py
method: random
project: mlpc_hyperparam_opt
metric:
  name: accuracy
  goal: maximize
parameters:
  hidden_layer_sizes:
    values: [(10,10), (30,30), (60,60), (90,90), (10,10,10), (30,30,30), (60,60,60), (90,90,90)]
  activation:
    values: ['identity', 'logistic', 'tanh', 'relu']
  solver:
    values: ['lbfgs','sgd','adam']
  alpha:
    values: [0.0001,0.0005,0.001, 0.005, 0.01, 0.05]
  learning_rate:
    values: ['constant', 'invscaling', 'adaptive']
  momentum:
    values: [0.9, 0.8, 0.7, 0.6, 0.5]
