wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1647439686
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      4: 3.9.7
      5: 0.12.11
      8:
      - 1
      - 5
    viz:
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
